version: '3.7'
services:
  db1:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db1
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
